# Generated by Django 3.1.2 on 2020-10-19 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import insta.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insta', '0002_remove_profile_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='profile',
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='pictures',
            field=models.ImageField(null=True, upload_to=insta.models.user_directory_path, verbose_name='Picture'),
        ),
        migrations.AddField(
            model_name='stream',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insta.post'),
            preserve_default=False,
        ),
    ]
