# Generated by Django 3.1.2 on 2020-10-19 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_auto_20201019_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pictures',
        ),
    ]
