# Generated by Django 3.1.2 on 2020-10-18 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
