# Generated by Django 3.1.2 on 2020-10-18 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0007_auto_20201018_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='image_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
    ]
