# Generated by Django 3.1.2 on 2020-10-18 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0011_auto_20201018_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='description',
        ),
    ]
