# Generated by Django 3.1.2 on 2020-10-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0015_auto_20201018_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(max_length=1000, null=True, verbose_name='Caption'),
        ),
    ]
