# Generated by Django 3.1.2 on 2020-10-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0016_auto_20201018_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
